risky: false
preset: psr2
version: 7
finder:
  exclude:
    - "app/Widgets/**/Views/"
    - "app/Widgets/**/Migrations/"
    - "bootstrap/cache/"
    - "config/home_photos.php"
    - "database"
    - "node_modules"
    - "public"
    - "resources"
    - "storage"
    - "stubs"
    - "vendor"
